import Head from "next/head";
import styles from "src/common/styles/Home.module.css";
import Header from "src/common/components/header";
import Footer from "src/common/components/footer";
import Home from "src/common/components/Home";

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Home />

      <Footer />
    </div>
  );
}
